### ISSUE TITLE
Can this template add tags for every article?

### ISSUE THREAD

**Issue by amulil** [flexdinesh/blogster#12]
if someone have many ariticles, he will need a tag to classify articles.

**Comment by flexdinesh** [comment]
I have done implemented tags (I call them labels) in my blog. Take a look here: https://github.com/flexdinesh/dineshpandiyan.com/blob/dcea33e9fc20d4ef041127136e03c9cb28765c41/src/lib/markdoc/frontmatter.schema.ts#L3

**Comment by amulil** [comment]
Thanks, it's awesome.
