### ISSUE TITLE
Can I remake the Blogster Newspaper theme on a newer Astro version?

### ISSUE THREAD

**Issue by noClaps** [flexdinesh/blogster#27]
Hey, I really liked your Blogster Newspaper theme, and I was wondering if I had permission from you to remake it with newer Astro features like Markdoc integration and Content Collections? I'll credit you in the README, of course. I'll also publish it under a different name (I was thinking Journal).

**Comment by flexdinesh** [comment]
I have no objections. Glad that Blogster has been a source of inspiration to you. Good luck!

**Comment by noClaps** [comment]
Hey I've just made the theme at https://github.com/noClaps/themes if you wanna check it out.

Edit: Taken down.

**Comment by flexdinesh** [comment]
Looks great!

**Comment by jjaimealeman** [comment]
> Hey I've just made the theme at https://github.com/noClaps/themes if you wanna check it out.

Screenshots would be nice 😉

**Comment by noClaps** [comment]
> Screenshots would be nice 😉

I've done one better, I've added a demo!

https://journal.themes.zerolimits.dev

Also please open any future suggestions on the [themes](https://github.com/noClaps/themes) repo.

**Comment by marcfon** [comment]
@noClaps I would love to see your version but the repo seems to be down. Is there a new location?

**Comment by noClaps** [comment]
Oh, I took it down because I don't think anyone was using it and I stopped using Astro myself, sorry! I should probably update the original comment. I'll also close this issue since it's no longer relevant.
