### ISSUE TITLE
Using the Markdown renderer seems to create a size change in the document (making it shift)

### ISSUE THREAD

**Issue by mvittiglio** [flexdinesh/blogster#30]
Not the end of the world but thought I would point it out. Check out the transition between [the blog page](https://blogster-sleek.netlify.app/blog) and [a blog entry](https://blogster-sleek.netlify.app/blog/basic-markdown-style-guide/). If you look at the nav bar to the top there is definitely a jitter back and forth. I managed to narrow it down to the markdown renderer but don't know how to handle it from here since my CSS-fu is still white-belt grade.

**Comment by mvittiglio** [comment]
Figured it out, the shift is because, on long enough posts, the scroll bar on the right renders and it causes a recentering of the main page. Feel free to close if this is expected behavior.

**Comment by flexdinesh** [comment]
[scrollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) should help with that. I use `scrollbar-gutter: stable;` in my websites to ensure the content doesn't shift when navigating from a page without scrollbar to a page with scrollbar.

**Comment by mvittiglio** [comment]
Scrollbar-gutter approach worked great. Thank you!
